name: chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutterfire_cli: ^0.2.7
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  animated_text_kit: ^4.2.2
  modal_progress_hud_nsn: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - images/