// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZShPOeUfglTIJM6iQ56MA-BwiHd3wDyc',
    appId: '1:376253655479:web:f6d1ab0fc8f322fb2f2032',
    messagingSenderId: '376253655479',
    projectId: 'chat-8509c',
    authDomain: 'chat-8509c.firebaseapp.com',
    storageBucket: 'chat-8509c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgs61Ektcdq3BdLX9jQA3sWBQl047bPqw',
    appId: '1:376253655479:android:e8b310f300590fa62f2032',
    messagingSenderId: '376253655479',
    projectId: 'chat-8509c',
    storageBucket: 'chat-8509c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCREc9XUNkCJhkIyXPEF54p0dHH_B51Bew',
    appId: '1:376253655479:ios:75329078ec9b3fc12f2032',
    messagingSenderId: '376253655479',
    projectId: 'chat-8509c',
    storageBucket: 'chat-8509c.appspot.com',
    iosClientId: '376253655479-65jabm08kuvhahuea10usu4igs3pj0m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCREc9XUNkCJhkIyXPEF54p0dHH_B51Bew',
    appId: '1:376253655479:ios:b0b476bb8de9d68d2f2032',
    messagingSenderId: '376253655479',
    projectId: 'chat-8509c',
    storageBucket: 'chat-8509c.appspot.com',
    iosClientId: '376253655479-7rds3eunk7de0i996e1r8fvmjl03dhfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
